server:
  port: 8080
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mariadb://localhost:3306/remember_db
    driver-class-name: org.mariadb.jdbc.Driver
    username: jeeewan
    password: 1234

logging.level:
  org.hibernate.SQL: debug