spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: ${aws.url}
    driver-class-name: ${aws.driver-class-name}
    username: ${aws.username}
    password: ${aws.password}

logging.level:
  org.hibernate.SQL: debug